import { z } from "zod";

export const serverProperties = z.object({
  "accepts-transfers": z.boolean().default(false),
  "allow-flight": z.boolean().default(false),
  "broadcast-console-to-ops": z.boolean().default(true),
  "broadcast-rcon-to-ops": z.boolean().default(true),
  "bug-report-link": z.string().default(""),
  "chat-spam-threshold-seconds": z.number().int().default(10),
  "command-spam-threshold-seconds": z.number().int().default(10),
  difficulty: z.enum(["peaceful", "easy", "normal", "hard"]).default("easy"),
  "enable-code-of-conduct": z.boolean().default(false),
  "enable-jmx-monitoring": z.boolean().default(false),
  "enable-query": z.boolean().default(false),
  "enable-rcon": z.boolean().default(false),
  "enable-status": z.boolean().default(true),
  "enforce-secure-profile": z.boolean().default(true),
  "enforce-whitelist": z.boolean().default(false),
  "entity-broadcast-range-percentage": z.number().int().min(10).max(1000).default(100),
  "force-gamemode": z.boolean().default(false),
  "function-permission-level": z.number().int().min(1).max(4).default(2),
  gamemode: z.enum(["survival", "creative", "adventure", "spectator"]).default("survival"),
  "generate-structures": z.boolean().default(true),
  "generator-settings": z.string().default("{}"),
  hardcore: z.boolean().default(false),
  "hide-online-players": z.boolean().default(false),
  "initial-disabled-packs": z.string().default(""),
  "initial-enabled-packs": z.string().default("vanilla"),
  "level-name": z.string().default("world"),
  "level-seed": z.string().default(""),
  "level-type": z
    .enum([
      "minecraft:normal",
      "minecraft:flat",
      "minecraft:large_biomes",
      "minecraft:amplified",
      "minecraft:single_biome_surface",
    ])
    .default("minecraft:normal"),
  "log-ips": z.boolean().default(true),
  "management-server-enabled": z.boolean().default(false),
  "management-server-host": z.string().default("localhost"),
  "management-server-port": z.number().int().default(0),
  "management-server-secret": z.string().default(""),
  "management-server-tls-enabled": z.boolean().default(true),
  "management-server-tls-keystore": z.string().default(""),
  "management-server-tls-keystore-password": z.string().default(""),
  "max-chained-neighbor-updates": z.number().int().default(1000000),
  "max-players": z.number().int().min(0).max(2147483647).default(20),
  "max-tick-time": z.number().int().min(-1).default(60000),
  "max-world-size": z.number().int().min(1).max(29999984).default(29999984),
  motd: z.string().default("A Minecraft Server"),
  "network-compression-threshold": z.number().int().default(256),
  "online-mode": z.boolean().default(true),
  "op-permission-level": z.number().int().min(0).max(4).default(4),
  "pause-when-empty-seconds": z.number().int().default(60),
  "player-idle-timeout": z.number().int().default(0),
  "prevent-proxy-connections": z.boolean().default(false),
  "query.port": z.number().int().min(1).max(65534).default(25565),
  "rate-limit": z.number().int().default(0),
  "rcon.password": z.string().default(""),
  "rcon.port": z.number().int().min(1).max(65534).default(25575),
  "region-file-compression": z.enum(["deflate", "lz4", "none"]).default("deflate"),
  "require-resource-pack": z.boolean().default(false),
  "resource-pack": z.string().default(""),
  "resource-pack-id": z.string().uuid().or(z.literal("")).default(""),
  "resource-pack-prompt": z.string().default(""),
  "resource-pack-sha1": z.string().default(""),
  "server-ip": z.string().default(""),
  "server-port": z.number().int().min(1).max(65534).default(25565),
  "simulation-distance": z.number().int().min(3).max(32).default(10),
  "spawn-protection": z.number().int().default(16),
  "status-heartbeat-interval": z.number().int().default(0),
  "sync-chunk-writes": z.boolean().default(true),
  "text-filtering-config": z.string().default(""),
  "text-filtering-version": z.number().int().min(0).max(1).default(0),
  "use-native-transport": z.boolean().default(true),
  "view-distance": z.number().int().min(3).max(32).default(10),
  "white-list": z.boolean().default(false),
});

export type ServerProperties = z.infer<typeof serverPropertiesSchema>;
